# Generated by Django 5.2.8 on 2025-12-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.FileField(upload_to='certificados')),
                ('fechaGenerado', models.DateField(auto_now_add=True)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curso.inscripcion')),
            ],
        ),
    ]
