# Generated by Django 5.2.7 on 2025-10-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='lugarTrabajo',
        ),
    ]
