# Generated by Django 5.2.8 on 2025-12-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='documentoFrontal',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='documentoPosterior',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fechaNacimiento',
        ),
    ]
