# Generated by Django 5.2.8 on 2025-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_alumno_documentofrontal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apellido',
        ),
        migrations.AddField(
            model_name='profile',
            name='apellidoMaterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='apellidoPaterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
