# Generated by Django 5.2.7 on 2025-10-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_alumno_lugartrabajo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fechaNaciento',
            new_name='fechaNacimiento',
        ),
    ]
