# Generated by Django 5.2.8 on 2025-12-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_profile_apellido_profile_apellidomaterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
