# Generated by Django 5.2.7 on 2025-10-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_fechanaciento_profile_fechanacimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permiso',
        ),
    ]
