# Generated by Django 5.2.7 on 2025-10-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fechaInscripcion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
