# Generated by Django 5.2.7 on 2025-10-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_alumno_fechainscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='acreditacion',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='fechaVencimientoAcreditacion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fechaNacimiento',
        ),
        migrations.AddField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('docente', 'Docente'), ('alumno', 'Alumno')], default='alumno', max_length=20),
        ),
    ]
