# Generated by Django 5.2.7 on 2025-11-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_profile_direccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
