# Generated by Django 5.2.7 on 2025-11-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_delete_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='documentosEntregado',
        ),
    ]
