# Generated by Django 5.2.8 on 2025-12-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='curso.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales/')),
                ('link', models.URLField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'VIDEO'), ('LINK', 'Link'), ('OTRO', 'Otro')], default='PDF', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='curso.modulo')),
            ],
        ),
    ]
