# Generated by Django 5.2.7 on 2025-11-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinscripcion',
            name='cursoInteres',
        ),
    ]
