# Generated by Django 5.2.7 on 2025-10-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
