# Generated by Django 5.2.7 on 2025-11-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion',
            name='cursoInteres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinscripiones', to='curso.curso'),
        ),
    ]
