# Generated by Django 5.2.7 on 2025-11-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_remove_preinscripcion_cursointeres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='curso.curso'),
        ),
    ]
