# Generated by Django 5.2.8 on 2025-12-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_modulo_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
