# Generated by Django 5.2.7 on 2025-11-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_alter_preinscripcion_cursointeres'),
        ('registration', '0012_remove_alumno_documentosentregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='registration.docente'),
        ),
    ]
