# Generated by Django 5.2.7 on 2025-11-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_alter_inscripcion_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado')], default='Pendiente', max_length=20),
        ),
    ]
