# Generated by Django 5.2.7 on 2025-11-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='cursoInteres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
    ]
