# Generated by Django 5.2.8 on 2025-12-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_alter_material_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinscripcion',
            name='documentoFrontal',
        ),
        migrations.RemoveField(
            model_name='preinscripcion',
            name='documentoPosterior',
        ),
        migrations.RemoveField(
            model_name='preinscripcion',
            name='fechaNacimiento',
        ),
    ]
