# Generated by Django 5.2.8 on 2025-12-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_remove_preinscripcion_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
