# Generated by Django 5.2.8 on 2025-12-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion',
            name='fechaPostulacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
