# Generated by Django 5.2.8 on 2025-12-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0009_alter_preinscripcion_fechapostulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
